import { Card, Icon, Link, Text, icons, space } from '@scalar/design-system';
import { BOARD } from './data.js';
import { StatTile } from './StatTile.js';

/** Board Presentations — every block is variable length: wraps, never clips or truncates. */
export function BoardPresentationsCard({ variant }: { variant: keyof typeof BOARD }) {
  const deck = BOARD[variant];
  return (
    <Card
      title="Board Presentations"
      action={
        <Link href="#/board-deck-source" target="_blank" rel="noopener noreferrer">
          View Presentation <Icon size="xs" tone="inherit"><icons.OpenInNew /></Icon>
        </Link>
      }
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: space.m }}>
        <Text step="s" tone="tertiary">{deck.name} — {deck.date}</Text>
        <Text step="m">{deck.overview}</Text>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: space.s }}>
          {deck.callouts.map((c) => <StatTile key={c.label} label={c.label} value={c.value} />)}
        </div>
        <div>
          <Text as="span" step="s" weight="semiBold" tone="secondary">Highlights</Text>
          <ul style={{ margin: 0, paddingInlineStart: space.l, display: 'flex', flexDirection: 'column', gap: space.xs }}>
            {deck.highlights.map((h) => <li key={h}><Text as="span" step="m">{h}</Text></li>)}
          </ul>
        </div>
        <Text step="s" tone="tertiary">Summary generated by AI from the uploaded board deck. Check figures against the source.</Text>
      </div>
    </Card>
  );
}
