/**
 * Parses src/styles/tokens.css and emits the generated TypeScript token maps.
 * The CSS is the single source of truth; this file never invents a value.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const css = readFileSync(join(root, 'src/styles/tokens.css'), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');

// Collect `selector { ...decls }` blocks, ignoring @media wrappers (we only
// need the explicit [data-theme='dark'] block, which duplicates the media one).
const blocks = [];
const re = /([^{}]+)\{([^{}]*)\}/g;
let m;
while ((m = re.exec(css))) {
  const selector = m[1].trim().replace(/\s+/g, ' ');
  if (selector.startsWith('@')) continue;
  const decls = {};
  for (const line of m[2].split(';')) {
    const i = line.indexOf(':');
    if (i === -1) continue;
    const name = line.slice(0, i).trim();
    if (!name.startsWith('--')) continue;
    decls[name] = line.slice(i + 1).trim();
  }
  blocks.push({ selector, decls });
}

const merge = (pred) =>
  blocks.filter((b) => pred(b.selector)).reduce((acc, b) => Object.assign(acc, b.decls), {});

const lightAll = merge((s) => s === ':root' || s === ":root, :root[data-theme='light']");
const darkOnly = merge((s) => s === ":root[data-theme='dark']");
const dl = merge((s) => s === ":root[data-viewport='desktop-large']");
const mob = merge((s) => s === ":root[data-viewport='mobile']");

const pick = (obj, prefix) =>
  Object.fromEntries(Object.entries(obj).filter(([k]) => k.startsWith(prefix)));

const semanticLight = pick(lightAll, '--color-');
const primitives = pick(lightAll, '--primitive-');
const colorLight = Object.fromEntries(
  Object.entries(semanticLight).filter(([k]) => !k.startsWith('--primitive-')),
);

const scales = {};
for (const p of ['--space-', '--radius-', '--size-', '--breakpoint-', '--border-width-', '--z-', '--duration-', '--easing-', '--elevation-']) {
  Object.assign(scales, pick(lightAll, p));
}
const type = {};
for (const p of ['--font-', '--line-height-', '--letter-spacing-']) Object.assign(type, pick(lightAll, p));

const json = {
  meta: {
    system: 'Scalar Design System',
    version: '1.1',
    source: {
      tokens: 'anrnTIJKgu27zV224h7vON (Scalar_Design_System-v1.1)',
      components: 'Z4MtKOfkNEzhMYJzN1q3kR (Scalar_Design_System-Components)',
    },
  },
  primitives,
  color: Object.fromEntries(
    Object.keys(colorLight).map((k) => [k, { light: colorLight[k], dark: darkOnly[k] ?? colorLight[k] }]),
  ),
  scales,
  type: {
    desktop: type,
    'desktop-large': { ...type, ...dl },
    mobile: { ...type, ...mob },
  },
};

writeFileSync(join(root, 'src/tokens/tokens.json'), JSON.stringify(json, null, 2) + '\n');

const names = (obj) => Object.keys(obj).sort();
const union = (arr) => arr.map((n) => `  | '${n}'`).join('\n');

const ts = `/* AUTO-GENERATED by scripts/gen-tokens.mjs — do not edit by hand.
 * Source of truth: src/styles/tokens.css (extracted from Figma v1.1).
 */

/** Every semantic colour token in the system. ${Object.keys(colorLight).length} tokens. */
export type ColorToken =
${union(names(colorLight))};

/** Spacing, radius, sizing, breakpoint, elevation and motion tokens. */
export type ScaleToken =
${union(names(scales))};

/** Typography tokens. Values shift with the viewport mode (contract rule R6). */
export type TypeToken =
${union(names(type))};

/** Primitive colour steps. Reference only — never bind product UI (rule R1). */
export type PrimitiveToken =
${union(names(primitives))};

export type AnyToken = ColorToken | ScaleToken | TypeToken;

/** Raw Light/Dark values for every semantic colour token. */
export const colorValues: Record<ColorToken, { light: string; dark: string }> =
  ${JSON.stringify(json.color, null, 2).replace(/\n/g, '\n  ')} as Record<ColorToken, { light: string; dark: string }>;

/** Raw values for the mode-independent scales. */
export const scaleValues: Record<ScaleToken, string> =
  ${JSON.stringify(scales, null, 2).replace(/\n/g, '\n  ')} as Record<ScaleToken, string>;

/** Raw typography values per viewport mode. */
export const typeValues: Record<'desktop' | 'desktop-large' | 'mobile', Record<TypeToken, string>> =
  ${JSON.stringify(json.type, null, 2).replace(/\n/g, '\n  ')} as Record<'desktop' | 'desktop-large' | 'mobile', Record<TypeToken, string>>;

/** Primitive colour steps, for documentation and tooling only. */
export const primitiveValues: Record<PrimitiveToken, string> =
  ${JSON.stringify(primitives, null, 2).replace(/\n/g, '\n  ')} as Record<PrimitiveToken, string>;
`;

writeFileSync(join(root, 'src/tokens/generated.ts'), ts);

console.log(
  `generated: ${Object.keys(colorLight).length} colour, ${Object.keys(scales).length} scale, ` +
    `${Object.keys(type).length} type, ${Object.keys(primitives).length} primitive tokens`,
);
