/**
 * Compiles the Material Symbols listed in src/components/icon/material-icons.json
 * into src/components/icon/material.tsx — one tiny component per icon, so the
 * package ships only the icons the product uses and has no runtime dependency.
 *
 * Source: @material-symbols/svg-400 (Google Material Symbols, Apache-2.0).
 *   npm run gen:icons
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(readFileSync(join(root, 'src/components/icon/material-icons.json'), 'utf8'));
const src = join(root, 'node_modules/@material-symbols/svg-400', manifest.style);

const pascal = (name) => name.split('_').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
const names = [...new Set(manifest.icons)].sort();
const missing = names.filter((n) => !existsSync(join(src, `${n}.svg`)));
if (missing.length) {
  console.error(`✗ not in Material Symbols (${manifest.style}): ${missing.join(', ')}`);
  process.exit(1);
}

let out = `/**
 * Material Symbols (${manifest.style}, weight 400) — the Scalar product icon set.
 * GENERATED by scripts/gen-icons.mjs from material-icons.json. Do not edit.
 *
 * Each export is an SVG body for \`Icon\`: <Icon><icons.Search /></Icon>.
 * Glyphs are drawn in Material's 960-unit space and mapped onto Icon's 24px
 * viewBox; they fill with currentColor, so Icon's tone tints them.
 * Google Material Symbols are licensed Apache-2.0.
 */
import type { ReactElement } from 'react';

const T = 'scale(0.025) translate(0 960)';

`;
for (const n of names) {
  const svg = readFileSync(join(src, `${n}.svg`), 'utf8');
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
  const body = paths.map((d) => `<path d="${d}" />`).join('');
  out += `/** Material Symbol \`${n}\` */\nexport const ${pascal(n)} = (): ReactElement => <g transform={T} fill="currentColor">${body}</g>;\n`;
}
out += `\n/** Every icon name in this set, in Material's snake_case. */\nexport const materialIconNames = ${JSON.stringify(names)} as const;\n`;
writeFileSync(join(root, 'src/components/icon/material.tsx'), out);
console.log(`✓ ${names.length} Material Symbols written to src/components/icon/material.tsx`);
