/* AUTO-GENERATED by scripts/gen-tokens.mjs — do not edit by hand.
 * Source of truth: src/styles/tokens.css (extracted from Figma v1.1).
 */

/** Every semantic colour token in the system. 153 tokens. */
export type ColorToken =
  | '--color-bg-ai'
  | '--color-bg-ai-subtle'
  | '--color-bg-brand'
  | '--color-bg-brand-hover'
  | '--color-bg-brand-pressed'
  | '--color-bg-brand-subtle'
  | '--color-bg-disabled'
  | '--color-bg-inverse'
  | '--color-bg-negative'
  | '--color-bg-negative-hover'
  | '--color-bg-negative-pressed'
  | '--color-bg-negative-subtle'
  | '--color-bg-on-brand'
  | '--color-bg-page'
  | '--color-bg-positive'
  | '--color-bg-positive-hover'
  | '--color-bg-positive-pressed'
  | '--color-bg-positive-subtle'
  | '--color-bg-subtle'
  | '--color-bg-surface'
  | '--color-bg-surface-raised'
  | '--color-bg-warning'
  | '--color-bg-warning-hover'
  | '--color-bg-warning-pressed'
  | '--color-bg-warning-subtle'
  | '--color-chart-axis'
  | '--color-chart-grid'
  | '--color-chart-negative'
  | '--color-chart-positive'
  | '--color-chart-series-1'
  | '--color-chart-series-1-subtle'
  | '--color-chart-series-2'
  | '--color-chart-series-2-subtle'
  | '--color-chart-series-3'
  | '--color-chart-series-3-subtle'
  | '--color-chart-series-4'
  | '--color-chart-series-4-subtle'
  | '--color-chart-series-5'
  | '--color-chart-series-5-subtle'
  | '--color-chart-series-6'
  | '--color-chart-series-6-subtle'
  | '--color-chart-series-7'
  | '--color-chart-series-7-subtle'
  | '--color-chart-series-8'
  | '--color-chart-series-8-subtle'
  | '--color-chart-total'
  | '--color-command-company-action-background'
  | '--color-command-company-action-primary'
  | '--color-command-company-action-text'
  | '--color-command-firm-action-background'
  | '--color-command-firm-action-primary'
  | '--color-command-firm-action-text'
  | '--color-data-document-background'
  | '--color-data-document-primary'
  | '--color-data-document-text'
  | '--color-data-measurement-date-background'
  | '--color-data-measurement-date-primary'
  | '--color-data-measurement-date-text'
  | '--color-data-version-background'
  | '--color-data-version-primary'
  | '--color-data-version-text'
  | '--color-destination-page-background'
  | '--color-destination-page-primary'
  | '--color-destination-page-text'
  | '--color-entity-company-background'
  | '--color-entity-company-primary'
  | '--color-entity-company-text'
  | '--color-entity-firm-background'
  | '--color-entity-firm-primary'
  | '--color-entity-firm-text'
  | '--color-icon-ai'
  | '--color-icon-brand'
  | '--color-icon-brand-hover'
  | '--color-icon-brand-pressed'
  | '--color-icon-disabled'
  | '--color-icon-inverse'
  | '--color-icon-negative'
  | '--color-icon-negative-hover'
  | '--color-icon-negative-pressed'
  | '--color-icon-on-brand'
  | '--color-icon-on-brand-inactive'
  | '--color-icon-on-brand-muted'
  | '--color-icon-on-brand-subtle'
  | '--color-icon-positive'
  | '--color-icon-positive-hover'
  | '--color-icon-positive-pressed'
  | '--color-icon-primary'
  | '--color-icon-secondary'
  | '--color-icon-warning'
  | '--color-icon-warning-hover'
  | '--color-icon-warning-pressed'
  | '--color-overlay-medium'
  | '--color-overlay-scrim'
  | '--color-overlay-strong'
  | '--color-overlay-subtle'
  | '--color-shadow-ambient'
  | '--color-shadow-key'
  | '--color-stroke-ai'
  | '--color-stroke-brand'
  | '--color-stroke-brand-hover'
  | '--color-stroke-brand-pressed'
  | '--color-stroke-control'
  | '--color-stroke-default'
  | '--color-stroke-disabled'
  | '--color-stroke-divider'
  | '--color-stroke-focus'
  | '--color-stroke-negative'
  | '--color-stroke-negative-hover'
  | '--color-stroke-negative-pressed'
  | '--color-stroke-on-brand'
  | '--color-stroke-positive'
  | '--color-stroke-positive-hover'
  | '--color-stroke-positive-pressed'
  | '--color-stroke-strong'
  | '--color-stroke-subtle'
  | '--color-stroke-warning'
  | '--color-stroke-warning-hover'
  | '--color-stroke-warning-pressed'
  | '--color-text-ai'
  | '--color-text-brand'
  | '--color-text-brand-hover'
  | '--color-text-brand-pressed'
  | '--color-text-disabled'
  | '--color-text-editable'
  | '--color-text-inverse'
  | '--color-text-link'
  | '--color-text-link-hover'
  | '--color-text-link-pressed'
  | '--color-text-negative'
  | '--color-text-negative-hover'
  | '--color-text-negative-pressed'
  | '--color-text-on-ai'
  | '--color-text-on-brand'
  | '--color-text-on-brand-inactive'
  | '--color-text-on-brand-muted'
  | '--color-text-on-brand-subtle'
  | '--color-text-on-disabled'
  | '--color-text-on-negative'
  | '--color-text-on-positive'
  | '--color-text-on-warning'
  | '--color-text-positive'
  | '--color-text-positive-hover'
  | '--color-text-positive-pressed'
  | '--color-text-primary'
  | '--color-text-secondary'
  | '--color-text-sourced'
  | '--color-text-tertiary'
  | '--color-text-warning'
  | '--color-text-warning-hover'
  | '--color-text-warning-pressed'
  | '--color-utility-neutral-background'
  | '--color-utility-neutral-primary'
  | '--color-utility-neutral-text';

/** Spacing, radius, sizing, breakpoint, elevation and motion tokens. */
export type ScaleToken =
  | '--border-width-m'
  | '--border-width-s'
  | '--breakpoint-desktop'
  | '--breakpoint-desktop-large'
  | '--breakpoint-mobile'
  | '--breakpoint-tablet'
  | '--breakpoint-tablet-small'
  | '--duration-fast'
  | '--duration-instant'
  | '--duration-moderate'
  | '--easing-decelerate'
  | '--easing-standard'
  | '--elevation-modal'
  | '--elevation-overlay'
  | '--elevation-raised'
  | '--radius-2xs'
  | '--radius-full'
  | '--radius-l'
  | '--radius-m'
  | '--radius-none'
  | '--radius-s'
  | '--radius-xl'
  | '--radius-xs'
  | '--size-avatar-l'
  | '--size-avatar-m'
  | '--size-avatar-s'
  | '--size-avatar-xl'
  | '--size-avatar-xs'
  | '--size-control-l'
  | '--size-control-m'
  | '--size-control-s'
  | '--size-icon-l'
  | '--size-icon-m'
  | '--size-icon-s'
  | '--size-icon-xl'
  | '--size-icon-xs'
  | '--size-row-compact'
  | '--size-target-comfortable'
  | '--size-target-dense'
  | '--size-target-minimum'
  | '--space-2xl'
  | '--space-2xs'
  | '--space-3xl'
  | '--space-4xl'
  | '--space-l'
  | '--space-m'
  | '--space-none'
  | '--space-s'
  | '--space-xl'
  | '--space-xs'
  | '--z-drawer'
  | '--z-modal'
  | '--z-overlay'
  | '--z-scrim'
  | '--z-sticky'
  | '--z-toast'
  | '--z-tooltip';

/** Typography tokens. Values shift with the viewport mode (contract rule R6). */
export type TypeToken =
  | '--font-family-default'
  | '--font-size-display-l'
  | '--font-size-display-m'
  | '--font-size-display-s'
  | '--font-size-heading-2xl'
  | '--font-size-heading-3xl'
  | '--font-size-heading-4xl'
  | '--font-size-heading-5xl'
  | '--font-size-heading-l'
  | '--font-size-heading-m'
  | '--font-size-heading-s'
  | '--font-size-heading-xl'
  | '--font-size-heading-xs'
  | '--font-size-label-l'
  | '--font-size-label-m'
  | '--font-size-label-s'
  | '--font-size-link-l'
  | '--font-size-link-m'
  | '--font-size-link-s'
  | '--font-size-overline-m'
  | '--font-size-overline-s'
  | '--font-size-text-2xl'
  | '--font-size-text-l'
  | '--font-size-text-m'
  | '--font-size-text-s'
  | '--font-size-text-xl'
  | '--font-weight-bold'
  | '--font-weight-light'
  | '--font-weight-regular'
  | '--font-weight-semi-bold'
  | '--letter-spacing-display-l'
  | '--letter-spacing-display-m'
  | '--letter-spacing-display-s'
  | '--letter-spacing-heading-2xl'
  | '--letter-spacing-heading-3xl'
  | '--letter-spacing-heading-4xl'
  | '--letter-spacing-heading-5xl'
  | '--letter-spacing-heading-l'
  | '--letter-spacing-heading-m'
  | '--letter-spacing-heading-s'
  | '--letter-spacing-heading-xl'
  | '--letter-spacing-heading-xs'
  | '--letter-spacing-label-l'
  | '--letter-spacing-label-m'
  | '--letter-spacing-label-s'
  | '--letter-spacing-link-l'
  | '--letter-spacing-link-m'
  | '--letter-spacing-link-s'
  | '--letter-spacing-overline-m'
  | '--letter-spacing-overline-s'
  | '--letter-spacing-text-2xl'
  | '--letter-spacing-text-l'
  | '--letter-spacing-text-m'
  | '--letter-spacing-text-s'
  | '--letter-spacing-text-xl'
  | '--line-height-display-l'
  | '--line-height-display-m'
  | '--line-height-display-s'
  | '--line-height-heading-2xl'
  | '--line-height-heading-3xl'
  | '--line-height-heading-4xl'
  | '--line-height-heading-5xl'
  | '--line-height-heading-l'
  | '--line-height-heading-m'
  | '--line-height-heading-s'
  | '--line-height-heading-xl'
  | '--line-height-heading-xs'
  | '--line-height-label-l'
  | '--line-height-label-m'
  | '--line-height-label-s'
  | '--line-height-link-l'
  | '--line-height-link-m'
  | '--line-height-link-s'
  | '--line-height-overline-m'
  | '--line-height-overline-s'
  | '--line-height-text-2xl'
  | '--line-height-text-l'
  | '--line-height-text-m'
  | '--line-height-text-s'
  | '--line-height-text-xl';

/** Primitive colour steps. Reference only — never bind product UI (rule R1). */
export type PrimitiveToken =
  | '--primitive-ai-100'
  | '--primitive-ai-200'
  | '--primitive-ai-300'
  | '--primitive-ai-400'
  | '--primitive-ai-50'
  | '--primitive-ai-500'
  | '--primitive-ai-600'
  | '--primitive-ai-700'
  | '--primitive-ai-800'
  | '--primitive-ai-900'
  | '--primitive-blue-100'
  | '--primitive-blue-200'
  | '--primitive-blue-300'
  | '--primitive-blue-400'
  | '--primitive-blue-50'
  | '--primitive-blue-500'
  | '--primitive-blue-600'
  | '--primitive-blue-700'
  | '--primitive-blue-800'
  | '--primitive-blue-900'
  | '--primitive-brand-100'
  | '--primitive-brand-200'
  | '--primitive-brand-300'
  | '--primitive-brand-400'
  | '--primitive-brand-50'
  | '--primitive-brand-500'
  | '--primitive-brand-600'
  | '--primitive-brand-700'
  | '--primitive-brand-800'
  | '--primitive-brand-900'
  | '--primitive-cyan-100'
  | '--primitive-cyan-200'
  | '--primitive-cyan-300'
  | '--primitive-cyan-400'
  | '--primitive-cyan-50'
  | '--primitive-cyan-500'
  | '--primitive-cyan-600'
  | '--primitive-cyan-700'
  | '--primitive-cyan-800'
  | '--primitive-cyan-900'
  | '--primitive-green-100'
  | '--primitive-green-200'
  | '--primitive-green-300'
  | '--primitive-green-400'
  | '--primitive-green-50'
  | '--primitive-green-500'
  | '--primitive-green-600'
  | '--primitive-green-700'
  | '--primitive-green-800'
  | '--primitive-green-900'
  | '--primitive-neutral-100'
  | '--primitive-neutral-200'
  | '--primitive-neutral-300'
  | '--primitive-neutral-400'
  | '--primitive-neutral-50'
  | '--primitive-neutral-500'
  | '--primitive-neutral-600'
  | '--primitive-neutral-700'
  | '--primitive-neutral-800'
  | '--primitive-neutral-900'
  | '--primitive-neutral-alpha-black-08'
  | '--primitive-neutral-alpha-black-16'
  | '--primitive-neutral-alpha-black-30'
  | '--primitive-neutral-alpha-black-40'
  | '--primitive-neutral-alpha-black-50'
  | '--primitive-neutral-alpha-black-60'
  | '--primitive-neutral-alpha-black-70'
  | '--primitive-neutral-alpha-white-30'
  | '--primitive-neutral-alpha-white-50'
  | '--primitive-neutral-alpha-white-70'
  | '--primitive-neutral-black'
  | '--primitive-neutral-white'
  | '--primitive-olive-100'
  | '--primitive-olive-200'
  | '--primitive-olive-300'
  | '--primitive-olive-400'
  | '--primitive-olive-50'
  | '--primitive-olive-500'
  | '--primitive-olive-600'
  | '--primitive-olive-700'
  | '--primitive-olive-800'
  | '--primitive-olive-900'
  | '--primitive-orange-100'
  | '--primitive-orange-200'
  | '--primitive-orange-300'
  | '--primitive-orange-400'
  | '--primitive-orange-50'
  | '--primitive-orange-500'
  | '--primitive-orange-600'
  | '--primitive-orange-700'
  | '--primitive-orange-800'
  | '--primitive-orange-900'
  | '--primitive-pink-100'
  | '--primitive-pink-200'
  | '--primitive-pink-300'
  | '--primitive-pink-400'
  | '--primitive-pink-50'
  | '--primitive-pink-500'
  | '--primitive-pink-600'
  | '--primitive-pink-700'
  | '--primitive-pink-800'
  | '--primitive-pink-900'
  | '--primitive-purple-100'
  | '--primitive-purple-200'
  | '--primitive-purple-300'
  | '--primitive-purple-400'
  | '--primitive-purple-50'
  | '--primitive-purple-500'
  | '--primitive-purple-600'
  | '--primitive-purple-700'
  | '--primitive-purple-800'
  | '--primitive-purple-900'
  | '--primitive-red-100'
  | '--primitive-red-200'
  | '--primitive-red-300'
  | '--primitive-red-400'
  | '--primitive-red-50'
  | '--primitive-red-500'
  | '--primitive-red-600'
  | '--primitive-red-700'
  | '--primitive-red-800'
  | '--primitive-red-900'
  | '--primitive-teal-100'
  | '--primitive-teal-200'
  | '--primitive-teal-300'
  | '--primitive-teal-400'
  | '--primitive-teal-50'
  | '--primitive-teal-500'
  | '--primitive-teal-600'
  | '--primitive-teal-700'
  | '--primitive-teal-800'
  | '--primitive-teal-900'
  | '--primitive-yellow-100'
  | '--primitive-yellow-200'
  | '--primitive-yellow-300'
  | '--primitive-yellow-400'
  | '--primitive-yellow-50'
  | '--primitive-yellow-500'
  | '--primitive-yellow-600'
  | '--primitive-yellow-700'
  | '--primitive-yellow-800'
  | '--primitive-yellow-900';

export type AnyToken = ColorToken | ScaleToken | TypeToken;

/** Raw Light/Dark values for every semantic colour token. */
export const colorValues: Record<ColorToken, { light: string; dark: string }> =
  {
    "--color-text-primary": {
      "light": "#0f172a",
      "dark": "#f8fafc"
    },
    "--color-text-secondary": {
      "light": "#1e293b",
      "dark": "#e3e8f0"
    },
    "--color-text-tertiary": {
      "light": "#475569",
      "dark": "#cbd5e1"
    },
    "--color-text-disabled": {
      "light": "#94a3b8",
      "dark": "#475569"
    },
    "--color-text-inverse": {
      "light": "#f8fafc",
      "dark": "#0f172a"
    },
    "--color-text-brand": {
      "light": "#0268c1",
      "dark": "#68b1f1"
    },
    "--color-text-brand-hover": {
      "light": "#02539a",
      "dark": "#9acbf6"
    },
    "--color-text-brand-pressed": {
      "light": "#013e73",
      "dark": "#cde5fa"
    },
    "--color-text-link": {
      "light": "#2a3ef4",
      "dark": "#9ea7fa"
    },
    "--color-text-link-hover": {
      "light": "#0a1cc2",
      "dark": "#ced3fd"
    },
    "--color-text-link-pressed": {
      "light": "#071592",
      "dark": "#e9ebfe"
    },
    "--color-text-positive": {
      "light": "#007e17",
      "dark": "#31c37b"
    },
    "--color-text-positive-hover": {
      "light": "#006012",
      "dark": "#7ed6a5"
    },
    "--color-text-positive-pressed": {
      "light": "#00420f",
      "dark": "#bbe8ce"
    },
    "--color-text-warning": {
      "light": "#996600",
      "dark": "#ffcc66"
    },
    "--color-text-warning-hover": {
      "light": "#664400",
      "dark": "#ffdd99"
    },
    "--color-text-warning-pressed": {
      "light": "#332200",
      "dark": "#ffeecc"
    },
    "--color-text-negative": {
      "light": "#cb0000",
      "dark": "#ff999c"
    },
    "--color-text-negative-hover": {
      "light": "#9c0000",
      "dark": "#ffc8c9"
    },
    "--color-text-negative-pressed": {
      "light": "#6c0003",
      "dark": "#ffe6e7"
    },
    "--color-text-ai": {
      "light": "#a614ff",
      "dark": "#d692ff"
    },
    "--color-text-sourced": {
      "light": "#007e17",
      "dark": "#31c37b"
    },
    "--color-text-editable": {
      "light": "#0268c1",
      "dark": "#68b1f1"
    },
    "--color-text-on-brand": {
      "light": "#ffffff",
      "dark": "#0f172a"
    },
    "--color-text-on-brand-subtle": {
      "light": "#f1f5f9",
      "dark": "#1e293b"
    },
    "--color-text-on-brand-muted": {
      "light": "#94a3b8",
      "dark": "#475569"
    },
    "--color-text-on-brand-inactive": {
      "light": "#9acbf6",
      "dark": "#013e73"
    },
    "--color-text-on-positive": {
      "light": "#ffffff",
      "dark": "#0f172a"
    },
    "--color-text-on-negative": {
      "light": "#ffffff",
      "dark": "#0f172a"
    },
    "--color-text-on-warning": {
      "light": "#0f172a",
      "dark": "#0f172a"
    },
    "--color-text-on-ai": {
      "light": "#ffffff",
      "dark": "#0f172a"
    },
    "--color-text-on-disabled": {
      "light": "#475569",
      "dark": "#cbd5e1"
    },
    "--color-bg-page": {
      "light": "#f8fafc",
      "dark": "#0f172a"
    },
    "--color-bg-surface": {
      "light": "#ffffff",
      "dark": "#1e293b"
    },
    "--color-bg-surface-raised": {
      "light": "#ffffff",
      "dark": "#334155"
    },
    "--color-bg-subtle": {
      "light": "#f1f5f9",
      "dark": "#1e293b"
    },
    "--color-bg-inverse": {
      "light": "#0f172a",
      "dark": "#f8fafc"
    },
    "--color-bg-disabled": {
      "light": "#e3e8f0",
      "dark": "#334155"
    },
    "--color-bg-brand": {
      "light": "#0268c1",
      "dark": "#3597ed"
    },
    "--color-bg-brand-hover": {
      "light": "#02539a",
      "dark": "#68b1f1"
    },
    "--color-bg-brand-pressed": {
      "light": "#013e73",
      "dark": "#9acbf6"
    },
    "--color-bg-on-brand": {
      "light": "#01294c",
      "dark": "#cde5fa"
    },
    "--color-bg-brand-subtle": {
      "light": "#e9f3fd",
      "dark": "#01294c"
    },
    "--color-bg-positive": {
      "light": "#007e17",
      "dark": "#00b04f"
    },
    "--color-bg-positive-hover": {
      "light": "#006012",
      "dark": "#31c37b"
    },
    "--color-bg-positive-pressed": {
      "light": "#00420f",
      "dark": "#7ed6a5"
    },
    "--color-bg-positive-subtle": {
      "light": "#e0f5e9",
      "dark": "#002409"
    },
    "--color-bg-warning": {
      "light": "#ffbb33",
      "dark": "#ffbb33"
    },
    "--color-bg-warning-hover": {
      "light": "#ffaa00",
      "dark": "#ffcc66"
    },
    "--color-bg-warning-pressed": {
      "light": "#cc8800",
      "dark": "#ffdd99"
    },
    "--color-bg-warning-subtle": {
      "light": "#fff7e8",
      "dark": "#332200"
    },
    "--color-bg-negative": {
      "light": "#cb0000",
      "dark": "#ff2f3d"
    },
    "--color-bg-negative-hover": {
      "light": "#9c0000",
      "dark": "#ff686e"
    },
    "--color-bg-negative-pressed": {
      "light": "#6c0003",
      "dark": "#ff999c"
    },
    "--color-bg-negative-subtle": {
      "light": "#ffe6e7",
      "dark": "#3b0104"
    },
    "--color-bg-ai": {
      "light": "#a614ff",
      "dark": "#c668ff"
    },
    "--color-bg-ai-subtle": {
      "light": "#fbf4ff",
      "dark": "#5d0095"
    },
    "--color-stroke-default": {
      "light": "#cbd5e1",
      "dark": "#334155"
    },
    "--color-stroke-subtle": {
      "light": "#e3e8f0",
      "dark": "#1e293b"
    },
    "--color-stroke-divider": {
      "light": "#e3e8f0",
      "dark": "#334155"
    },
    "--color-stroke-strong": {
      "light": "#475569",
      "dark": "#cbd5e1"
    },
    "--color-stroke-control": {
      "light": "#64748b",
      "dark": "#94a3b8"
    },
    "--color-stroke-focus": {
      "light": "#037de8",
      "dark": "#68b1f1"
    },
    "--color-stroke-disabled": {
      "light": "#e3e8f0",
      "dark": "#334155"
    },
    "--color-stroke-brand": {
      "light": "#0268c1",
      "dark": "#3597ed"
    },
    "--color-stroke-brand-hover": {
      "light": "#02539a",
      "dark": "#68b1f1"
    },
    "--color-stroke-brand-pressed": {
      "light": "#013e73",
      "dark": "#9acbf6"
    },
    "--color-stroke-on-brand": {
      "light": "#ffffff",
      "dark": "#0f172a"
    },
    "--color-stroke-positive": {
      "light": "#007e17",
      "dark": "#00b04f"
    },
    "--color-stroke-positive-hover": {
      "light": "#006012",
      "dark": "#31c37b"
    },
    "--color-stroke-positive-pressed": {
      "light": "#00420f",
      "dark": "#7ed6a5"
    },
    "--color-stroke-warning": {
      "light": "#996600",
      "dark": "#ffcc66"
    },
    "--color-stroke-warning-hover": {
      "light": "#664400",
      "dark": "#ffdd99"
    },
    "--color-stroke-warning-pressed": {
      "light": "#332200",
      "dark": "#ffeecc"
    },
    "--color-stroke-negative": {
      "light": "#cb0000",
      "dark": "#ff2f3d"
    },
    "--color-stroke-negative-hover": {
      "light": "#9c0000",
      "dark": "#ff686e"
    },
    "--color-stroke-negative-pressed": {
      "light": "#6c0003",
      "dark": "#ff999c"
    },
    "--color-stroke-ai": {
      "light": "#a614ff",
      "dark": "#d692ff"
    },
    "--color-icon-primary": {
      "light": "#0f172a",
      "dark": "#f8fafc"
    },
    "--color-icon-secondary": {
      "light": "#475569",
      "dark": "#94a3b8"
    },
    "--color-icon-inverse": {
      "light": "#f8fafc",
      "dark": "#0f172a"
    },
    "--color-icon-disabled": {
      "light": "#94a3b8",
      "dark": "#475569"
    },
    "--color-icon-brand": {
      "light": "#0268c1",
      "dark": "#3597ed"
    },
    "--color-icon-brand-hover": {
      "light": "#02539a",
      "dark": "#68b1f1"
    },
    "--color-icon-brand-pressed": {
      "light": "#013e73",
      "dark": "#9acbf6"
    },
    "--color-icon-positive": {
      "light": "#007e17",
      "dark": "#00b04f"
    },
    "--color-icon-positive-hover": {
      "light": "#006012",
      "dark": "#31c37b"
    },
    "--color-icon-positive-pressed": {
      "light": "#00420f",
      "dark": "#7ed6a5"
    },
    "--color-icon-warning": {
      "light": "#996600",
      "dark": "#ffcc66"
    },
    "--color-icon-warning-hover": {
      "light": "#664400",
      "dark": "#ffdd99"
    },
    "--color-icon-warning-pressed": {
      "light": "#332200",
      "dark": "#ffeecc"
    },
    "--color-icon-negative": {
      "light": "#cb0000",
      "dark": "#ff2f3d"
    },
    "--color-icon-negative-hover": {
      "light": "#9c0000",
      "dark": "#ff686e"
    },
    "--color-icon-negative-pressed": {
      "light": "#6c0003",
      "dark": "#ff999c"
    },
    "--color-icon-ai": {
      "light": "#a614ff",
      "dark": "#d692ff"
    },
    "--color-icon-on-brand": {
      "light": "#ffffff",
      "dark": "#0f172a"
    },
    "--color-icon-on-brand-subtle": {
      "light": "#f1f5f9",
      "dark": "#1e293b"
    },
    "--color-icon-on-brand-muted": {
      "light": "#94a3b8",
      "dark": "#475569"
    },
    "--color-icon-on-brand-inactive": {
      "light": "#cbd5e1",
      "dark": "#334155"
    },
    "--color-overlay-subtle": {
      "light": "#0000004d",
      "dark": "#ffffff4d"
    },
    "--color-overlay-medium": {
      "light": "#00000080",
      "dark": "#ffffff80"
    },
    "--color-overlay-strong": {
      "light": "#000000b2",
      "dark": "#ffffffb2"
    },
    "--color-overlay-scrim": {
      "light": "#00000080",
      "dark": "#00000099"
    },
    "--color-shadow-ambient": {
      "light": "#00000014",
      "dark": "#00000066"
    },
    "--color-shadow-key": {
      "light": "#00000029",
      "dark": "#00000099"
    },
    "--color-chart-series-1": {
      "light": "#8e1242",
      "dark": "#f088bd"
    },
    "--color-chart-series-2": {
      "light": "#808135",
      "dark": "#d3d392"
    },
    "--color-chart-series-3": {
      "light": "#cb0000",
      "dark": "#ff686e"
    },
    "--color-chart-series-4": {
      "light": "#046140",
      "dark": "#9ce8cd"
    },
    "--color-chart-series-5": {
      "light": "#013e73",
      "dark": "#3597ed"
    },
    "--color-chart-series-6": {
      "light": "#d26000",
      "dark": "#ffc790"
    },
    "--color-chart-series-7": {
      "light": "#5826d6",
      "dark": "#a77fff"
    },
    "--color-chart-series-8": {
      "light": "#0e7490",
      "dark": "#67e8f9"
    },
    "--color-chart-series-1-subtle": {
      "light": "#fce7f3",
      "dark": "#5f0c29"
    },
    "--color-chart-series-2-subtle": {
      "light": "#f3f3dd",
      "dark": "#49491d"
    },
    "--color-chart-series-3-subtle": {
      "light": "#ffc8c9",
      "dark": "#6c0003"
    },
    "--color-chart-series-4-subtle": {
      "light": "#cef3e6",
      "dark": "#046140"
    },
    "--color-chart-series-5-subtle": {
      "light": "#cde5fa",
      "dark": "#013e73"
    },
    "--color-chart-series-6-subtle": {
      "light": "#ffe0c4",
      "dark": "#6f3300"
    },
    "--color-chart-series-7-subtle": {
      "light": "#dfcfff",
      "dark": "#2e1571"
    },
    "--color-chart-series-8-subtle": {
      "light": "#cffafe",
      "dark": "#155e75"
    },
    "--color-chart-positive": {
      "light": "#007e17",
      "dark": "#00b04f"
    },
    "--color-chart-negative": {
      "light": "#cb0000",
      "dark": "#ff2f3d"
    },
    "--color-chart-total": {
      "light": "#0f172a",
      "dark": "#f8fafc"
    },
    "--color-chart-grid": {
      "light": "#e3e8f0",
      "dark": "#1e293b"
    },
    "--color-chart-axis": {
      "light": "#64748b",
      "dark": "#64748b"
    },
    "--color-entity-firm-primary": {
      "light": "#cc8800",
      "dark": "#ffbb33"
    },
    "--color-entity-firm-background": {
      "light": "#ffeecc",
      "dark": "#332200"
    },
    "--color-entity-firm-text": {
      "light": "#664400",
      "dark": "#ffcc66"
    },
    "--color-entity-company-primary": {
      "light": "#0268c1",
      "dark": "#3597ed"
    },
    "--color-entity-company-background": {
      "light": "#cde5fa",
      "dark": "#01294c"
    },
    "--color-entity-company-text": {
      "light": "#02539a",
      "dark": "#68b1f1"
    },
    "--color-data-document-primary": {
      "light": "#0a1cc2",
      "dark": "#3d4ff5"
    },
    "--color-data-document-background": {
      "light": "#ced3fd",
      "dark": "#020731"
    },
    "--color-data-document-text": {
      "light": "#0a1cc2",
      "dark": "#9ea7fa"
    },
    "--color-data-version-primary": {
      "light": "#007e17",
      "dark": "#00b04f"
    },
    "--color-data-version-background": {
      "light": "#bbe8ce",
      "dark": "#002409"
    },
    "--color-data-version-text": {
      "light": "#006012",
      "dark": "#31c37b"
    },
    "--color-data-measurement-date-primary": {
      "light": "#0891b2",
      "dark": "#22d3ee"
    },
    "--color-data-measurement-date-background": {
      "light": "#cffafe",
      "dark": "#164e63"
    },
    "--color-data-measurement-date-text": {
      "light": "#0e7490",
      "dark": "#67e8f9"
    },
    "--color-destination-page-primary": {
      "light": "#be185d",
      "dark": "#ea589e"
    },
    "--color-destination-page-background": {
      "light": "#fce7f3",
      "dark": "#2f0613"
    },
    "--color-destination-page-text": {
      "light": "#be185d",
      "dark": "#f6b7d9"
    },
    "--color-command-firm-action-primary": {
      "light": "#a614ff",
      "dark": "#c668ff"
    },
    "--color-command-firm-action-background": {
      "light": "#f5e6ff",
      "dark": "#5d0095"
    },
    "--color-command-firm-action-text": {
      "light": "#9100e9",
      "dark": "#d692ff"
    },
    "--color-command-company-action-primary": {
      "light": "#808135",
      "dark": "#c2c26b"
    },
    "--color-command-company-action-background": {
      "light": "#f3f3dd",
      "dark": "#303012"
    },
    "--color-command-company-action-text": {
      "light": "#666629",
      "dark": "#d3d392"
    },
    "--color-utility-neutral-primary": {
      "light": "#475569",
      "dark": "#94a3b8"
    },
    "--color-utility-neutral-background": {
      "light": "#f1f5f9",
      "dark": "#0f172a"
    },
    "--color-utility-neutral-text": {
      "light": "#475569",
      "dark": "#cbd5e1"
    }
  } as Record<ColorToken, { light: string; dark: string }>;

/** Raw values for the mode-independent scales. */
export const scaleValues: Record<ScaleToken, string> =
  {
    "--space-none": "0px",
    "--space-2xs": "2px",
    "--space-xs": "4px",
    "--space-s": "8px",
    "--space-m": "12px",
    "--space-l": "16px",
    "--space-xl": "24px",
    "--space-2xl": "32px",
    "--space-3xl": "48px",
    "--space-4xl": "64px",
    "--radius-none": "0px",
    "--radius-2xs": "2px",
    "--radius-xs": "4px",
    "--radius-s": "8px",
    "--radius-m": "16px",
    "--radius-l": "24px",
    "--radius-xl": "32px",
    "--radius-full": "9999px",
    "--size-icon-xs": "12px",
    "--size-icon-s": "16px",
    "--size-icon-m": "20px",
    "--size-icon-l": "24px",
    "--size-icon-xl": "32px",
    "--size-control-s": "32px",
    "--size-control-m": "40px",
    "--size-control-l": "48px",
    "--size-avatar-xs": "24px",
    "--size-avatar-s": "32px",
    "--size-avatar-m": "40px",
    "--size-avatar-l": "56px",
    "--size-avatar-xl": "80px",
    "--size-row-compact": "26px",
    "--size-target-dense": "24px",
    "--size-target-minimum": "44px",
    "--size-target-comfortable": "48px",
    "--breakpoint-mobile": "393px",
    "--breakpoint-tablet-small": "768px",
    "--breakpoint-tablet": "1024px",
    "--breakpoint-desktop": "1440px",
    "--breakpoint-desktop-large": "1920px",
    "--border-width-s": "1px",
    "--border-width-m": "2px",
    "--z-sticky": "100",
    "--z-drawer": "200",
    "--z-scrim": "300",
    "--z-modal": "400",
    "--z-overlay": "500",
    "--z-toast": "600",
    "--z-tooltip": "700",
    "--duration-instant": "100ms",
    "--duration-fast": "150ms",
    "--duration-moderate": "250ms",
    "--easing-standard": "cubic-bezier(0.2, 0, 0, 1)",
    "--easing-decelerate": "cubic-bezier(0, 0, 0, 1)",
    "--elevation-raised": "0 1px 3px 0 var(--color-shadow-ambient), 0 1px 2px 0 var(--color-shadow-key)",
    "--elevation-overlay": "0 8px 24px -4px var(--color-shadow-ambient), 0 2px 6px -1px var(--color-shadow-key)",
    "--elevation-modal": "0 24px 48px -12px var(--color-shadow-ambient), 0 8px 16px -4px var(--color-shadow-key)"
  } as Record<ScaleToken, string>;

/** Raw typography values per viewport mode. */
export const typeValues: Record<'desktop' | 'desktop-large' | 'mobile', Record<TypeToken, string>> =
  {
    "desktop": {
      "--font-family-default": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      "--font-weight-light": "300",
      "--font-weight-regular": "400",
      "--font-weight-semi-bold": "600",
      "--font-weight-bold": "700",
      "--font-size-display-s": "40px",
      "--font-size-display-m": "48px",
      "--font-size-display-l": "56px",
      "--font-size-heading-xs": "10px",
      "--font-size-heading-s": "12px",
      "--font-size-heading-m": "14px",
      "--font-size-heading-l": "16px",
      "--font-size-heading-xl": "18px",
      "--font-size-heading-2xl": "20px",
      "--font-size-heading-3xl": "24px",
      "--font-size-heading-4xl": "28px",
      "--font-size-heading-5xl": "32px",
      "--font-size-text-s": "12px",
      "--font-size-text-m": "14px",
      "--font-size-text-l": "16px",
      "--font-size-text-xl": "18px",
      "--font-size-text-2xl": "20px",
      "--font-size-label-s": "12px",
      "--font-size-label-m": "14px",
      "--font-size-label-l": "16px",
      "--font-size-link-s": "12px",
      "--font-size-link-m": "14px",
      "--font-size-link-l": "16px",
      "--font-size-overline-s": "12px",
      "--font-size-overline-m": "14px",
      "--line-height-display-s": "44px",
      "--line-height-display-m": "52px",
      "--line-height-display-l": "60px",
      "--line-height-heading-xs": "14px",
      "--line-height-heading-s": "16px",
      "--line-height-heading-m": "18px",
      "--line-height-heading-l": "20px",
      "--line-height-heading-xl": "24px",
      "--line-height-heading-2xl": "26px",
      "--line-height-heading-3xl": "32px",
      "--line-height-heading-4xl": "36px",
      "--line-height-heading-5xl": "40px",
      "--line-height-text-s": "16px",
      "--line-height-text-m": "20px",
      "--line-height-text-l": "24px",
      "--line-height-text-xl": "26px",
      "--line-height-text-2xl": "28px",
      "--line-height-label-s": "16px",
      "--line-height-label-m": "18px",
      "--line-height-label-l": "20px",
      "--line-height-link-s": "16px",
      "--line-height-link-m": "20px",
      "--line-height-link-l": "24px",
      "--line-height-overline-s": "16px",
      "--line-height-overline-m": "18px",
      "--letter-spacing-display-s": "-1.5px",
      "--letter-spacing-display-m": "-1.5px",
      "--letter-spacing-display-l": "-1.5px",
      "--letter-spacing-heading-xs": "0px",
      "--letter-spacing-heading-s": "0px",
      "--letter-spacing-heading-m": "0px",
      "--letter-spacing-heading-l": "-0.2px",
      "--letter-spacing-heading-xl": "-0.2px",
      "--letter-spacing-heading-2xl": "-0.5px",
      "--letter-spacing-heading-3xl": "-0.5px",
      "--letter-spacing-heading-4xl": "-1px",
      "--letter-spacing-heading-5xl": "-1px",
      "--letter-spacing-text-s": "0px",
      "--letter-spacing-text-m": "0px",
      "--letter-spacing-text-l": "0px",
      "--letter-spacing-text-xl": "0px",
      "--letter-spacing-text-2xl": "0px",
      "--letter-spacing-label-s": "0px",
      "--letter-spacing-label-m": "0px",
      "--letter-spacing-label-l": "0px",
      "--letter-spacing-link-s": "0px",
      "--letter-spacing-link-m": "0px",
      "--letter-spacing-link-l": "0px",
      "--letter-spacing-overline-s": "0.8px",
      "--letter-spacing-overline-m": "0.8px"
    },
    "desktop-large": {
      "--font-family-default": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      "--font-weight-light": "300",
      "--font-weight-regular": "400",
      "--font-weight-semi-bold": "600",
      "--font-weight-bold": "700",
      "--font-size-display-s": "48px",
      "--font-size-display-m": "56px",
      "--font-size-display-l": "64px",
      "--font-size-heading-xs": "12px",
      "--font-size-heading-s": "14px",
      "--font-size-heading-m": "16px",
      "--font-size-heading-l": "18px",
      "--font-size-heading-xl": "20px",
      "--font-size-heading-2xl": "24px",
      "--font-size-heading-3xl": "28px",
      "--font-size-heading-4xl": "32px",
      "--font-size-heading-5xl": "40px",
      "--font-size-text-s": "14px",
      "--font-size-text-m": "16px",
      "--font-size-text-l": "18px",
      "--font-size-text-xl": "20px",
      "--font-size-text-2xl": "24px",
      "--font-size-label-s": "14px",
      "--font-size-label-m": "16px",
      "--font-size-label-l": "18px",
      "--font-size-link-s": "14px",
      "--font-size-link-m": "16px",
      "--font-size-link-l": "18px",
      "--font-size-overline-s": "12px",
      "--font-size-overline-m": "14px",
      "--line-height-display-s": "52px",
      "--line-height-display-m": "60px",
      "--line-height-display-l": "68px",
      "--line-height-heading-xs": "16px",
      "--line-height-heading-s": "18px",
      "--line-height-heading-m": "20px",
      "--line-height-heading-l": "24px",
      "--line-height-heading-xl": "26px",
      "--line-height-heading-2xl": "32px",
      "--line-height-heading-3xl": "36px",
      "--line-height-heading-4xl": "40px",
      "--line-height-heading-5xl": "48px",
      "--line-height-text-s": "20px",
      "--line-height-text-m": "24px",
      "--line-height-text-l": "26px",
      "--line-height-text-xl": "28px",
      "--line-height-text-2xl": "32px",
      "--line-height-label-s": "18px",
      "--line-height-label-m": "20px",
      "--line-height-label-l": "24px",
      "--line-height-link-s": "20px",
      "--line-height-link-m": "24px",
      "--line-height-link-l": "26px",
      "--line-height-overline-s": "16px",
      "--line-height-overline-m": "18px",
      "--letter-spacing-display-s": "-1.5px",
      "--letter-spacing-display-m": "-1.5px",
      "--letter-spacing-display-l": "-1.5px",
      "--letter-spacing-heading-xs": "0px",
      "--letter-spacing-heading-s": "0px",
      "--letter-spacing-heading-m": "0px",
      "--letter-spacing-heading-l": "-0.2px",
      "--letter-spacing-heading-xl": "-0.2px",
      "--letter-spacing-heading-2xl": "-0.5px",
      "--letter-spacing-heading-3xl": "-0.5px",
      "--letter-spacing-heading-4xl": "-1px",
      "--letter-spacing-heading-5xl": "-1px",
      "--letter-spacing-text-s": "0px",
      "--letter-spacing-text-m": "0px",
      "--letter-spacing-text-l": "0px",
      "--letter-spacing-text-xl": "0px",
      "--letter-spacing-text-2xl": "0px",
      "--letter-spacing-label-s": "0px",
      "--letter-spacing-label-m": "0px",
      "--letter-spacing-label-l": "0px",
      "--letter-spacing-link-s": "0px",
      "--letter-spacing-link-m": "0px",
      "--letter-spacing-link-l": "0px",
      "--letter-spacing-overline-s": "0.8px",
      "--letter-spacing-overline-m": "0.8px"
    },
    "mobile": {
      "--font-family-default": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      "--font-weight-light": "300",
      "--font-weight-regular": "400",
      "--font-weight-semi-bold": "600",
      "--font-weight-bold": "700",
      "--font-size-display-s": "24px",
      "--font-size-display-m": "28px",
      "--font-size-display-l": "32px",
      "--font-size-heading-xs": "10px",
      "--font-size-heading-s": "12px",
      "--font-size-heading-m": "14px",
      "--font-size-heading-l": "16px",
      "--font-size-heading-xl": "18px",
      "--font-size-heading-2xl": "20px",
      "--font-size-heading-3xl": "24px",
      "--font-size-heading-4xl": "24px",
      "--font-size-heading-5xl": "28px",
      "--font-size-text-s": "12px",
      "--font-size-text-m": "14px",
      "--font-size-text-l": "16px",
      "--font-size-text-xl": "18px",
      "--font-size-text-2xl": "20px",
      "--font-size-label-s": "12px",
      "--font-size-label-m": "14px",
      "--font-size-label-l": "16px",
      "--font-size-link-s": "12px",
      "--font-size-link-m": "14px",
      "--font-size-link-l": "16px",
      "--font-size-overline-s": "12px",
      "--font-size-overline-m": "14px",
      "--line-height-display-s": "32px",
      "--line-height-display-m": "36px",
      "--line-height-display-l": "40px",
      "--line-height-heading-xs": "14px",
      "--line-height-heading-s": "16px",
      "--line-height-heading-m": "18px",
      "--line-height-heading-l": "20px",
      "--line-height-heading-xl": "24px",
      "--line-height-heading-2xl": "26px",
      "--line-height-heading-3xl": "32px",
      "--line-height-heading-4xl": "32px",
      "--line-height-heading-5xl": "36px",
      "--line-height-text-s": "16px",
      "--line-height-text-m": "20px",
      "--line-height-text-l": "24px",
      "--line-height-text-xl": "26px",
      "--line-height-text-2xl": "28px",
      "--line-height-label-s": "16px",
      "--line-height-label-m": "18px",
      "--line-height-label-l": "20px",
      "--line-height-link-s": "16px",
      "--line-height-link-m": "20px",
      "--line-height-link-l": "24px",
      "--line-height-overline-s": "16px",
      "--line-height-overline-m": "18px",
      "--letter-spacing-display-s": "-1.5px",
      "--letter-spacing-display-m": "-1.5px",
      "--letter-spacing-display-l": "-1.5px",
      "--letter-spacing-heading-xs": "0px",
      "--letter-spacing-heading-s": "0px",
      "--letter-spacing-heading-m": "0px",
      "--letter-spacing-heading-l": "-0.2px",
      "--letter-spacing-heading-xl": "-0.2px",
      "--letter-spacing-heading-2xl": "-0.5px",
      "--letter-spacing-heading-3xl": "-0.5px",
      "--letter-spacing-heading-4xl": "-1px",
      "--letter-spacing-heading-5xl": "-1px",
      "--letter-spacing-text-s": "0px",
      "--letter-spacing-text-m": "0px",
      "--letter-spacing-text-l": "0px",
      "--letter-spacing-text-xl": "0px",
      "--letter-spacing-text-2xl": "0px",
      "--letter-spacing-label-s": "0px",
      "--letter-spacing-label-m": "0px",
      "--letter-spacing-label-l": "0px",
      "--letter-spacing-link-s": "0px",
      "--letter-spacing-link-m": "0px",
      "--letter-spacing-link-l": "0px",
      "--letter-spacing-overline-s": "0.8px",
      "--letter-spacing-overline-m": "0.8px"
    }
  } as Record<'desktop' | 'desktop-large' | 'mobile', Record<TypeToken, string>>;

/** Primitive colour steps, for documentation and tooling only. */
export const primitiveValues: Record<PrimitiveToken, string> =
  {
    "--primitive-neutral-white": "#ffffff",
    "--primitive-neutral-black": "#000000",
    "--primitive-neutral-50": "#f8fafc",
    "--primitive-neutral-100": "#f1f5f9",
    "--primitive-neutral-200": "#e3e8f0",
    "--primitive-neutral-300": "#cbd5e1",
    "--primitive-neutral-400": "#94a3b8",
    "--primitive-neutral-500": "#64748b",
    "--primitive-neutral-600": "#475569",
    "--primitive-neutral-700": "#334155",
    "--primitive-neutral-800": "#1e293b",
    "--primitive-neutral-900": "#0f172a",
    "--primitive-neutral-alpha-white-30": "#ffffff4d",
    "--primitive-neutral-alpha-white-50": "#ffffff80",
    "--primitive-neutral-alpha-white-70": "#ffffffb2",
    "--primitive-neutral-alpha-black-08": "#00000014",
    "--primitive-neutral-alpha-black-16": "#00000029",
    "--primitive-neutral-alpha-black-30": "#0000004d",
    "--primitive-neutral-alpha-black-40": "#00000066",
    "--primitive-neutral-alpha-black-50": "#00000080",
    "--primitive-neutral-alpha-black-60": "#00000099",
    "--primitive-neutral-alpha-black-70": "#000000b2",
    "--primitive-brand-50": "#e9f3fd",
    "--primitive-brand-100": "#cde5fa",
    "--primitive-brand-200": "#9acbf6",
    "--primitive-brand-300": "#68b1f1",
    "--primitive-brand-400": "#3597ed",
    "--primitive-brand-500": "#037de8",
    "--primitive-brand-600": "#0268c1",
    "--primitive-brand-700": "#02539a",
    "--primitive-brand-800": "#013e73",
    "--primitive-brand-900": "#01294c",
    "--primitive-blue-50": "#e9ebfe",
    "--primitive-blue-100": "#ced3fd",
    "--primitive-blue-200": "#9ea7fa",
    "--primitive-blue-300": "#6d7bf8",
    "--primitive-blue-400": "#3d4ff5",
    "--primitive-blue-500": "#2a3ef4",
    "--primitive-blue-600": "#0a1cc2",
    "--primitive-blue-700": "#071592",
    "--primitive-blue-800": "#050e61",
    "--primitive-blue-900": "#020731",
    "--primitive-green-50": "#e0f5e9",
    "--primitive-green-100": "#bbe8ce",
    "--primitive-green-200": "#7ed6a5",
    "--primitive-green-300": "#31c37b",
    "--primitive-green-400": "#00b04f",
    "--primitive-green-500": "#009c1c",
    "--primitive-green-600": "#007e17",
    "--primitive-green-700": "#006012",
    "--primitive-green-800": "#00420f",
    "--primitive-green-900": "#002409",
    "--primitive-red-50": "#ffe6e7",
    "--primitive-red-100": "#ffc8c9",
    "--primitive-red-200": "#ff999c",
    "--primitive-red-300": "#ff686e",
    "--primitive-red-400": "#ff2f3d",
    "--primitive-red-500": "#fb0000",
    "--primitive-red-600": "#cb0000",
    "--primitive-red-700": "#9c0000",
    "--primitive-red-800": "#6c0003",
    "--primitive-red-900": "#3b0104",
    "--primitive-yellow-50": "#fff7e8",
    "--primitive-yellow-100": "#ffeecc",
    "--primitive-yellow-200": "#ffdd99",
    "--primitive-yellow-300": "#ffcc66",
    "--primitive-yellow-400": "#ffbb33",
    "--primitive-yellow-500": "#ffaa00",
    "--primitive-yellow-600": "#cc8800",
    "--primitive-yellow-700": "#996600",
    "--primitive-yellow-800": "#664400",
    "--primitive-yellow-900": "#332200",
    "--primitive-orange-50": "#fff1e4",
    "--primitive-orange-100": "#ffe0c4",
    "--primitive-orange-200": "#ffc790",
    "--primitive-orange-300": "#ffac5c",
    "--primitive-orange-400": "#ff9211",
    "--primitive-orange-500": "#ff7700",
    "--primitive-orange-600": "#d26000",
    "--primitive-orange-700": "#a04900",
    "--primitive-orange-800": "#6f3300",
    "--primitive-orange-900": "#3c1b00",
    "--primitive-teal-50": "#e9faf4",
    "--primitive-teal-100": "#cef3e6",
    "--primitive-teal-200": "#9ce8cd",
    "--primitive-teal-300": "#6bdcb3",
    "--primitive-teal-400": "#39d19a",
    "--primitive-teal-500": "#08c581",
    "--primitive-teal-600": "#07a46b",
    "--primitive-teal-700": "#058355",
    "--primitive-teal-800": "#046140",
    "--primitive-teal-900": "#03402a",
    "--primitive-cyan-50": "#e9fdff",
    "--primitive-cyan-100": "#cffafe",
    "--primitive-cyan-200": "#a5f3fc",
    "--primitive-cyan-300": "#67e8f9",
    "--primitive-cyan-400": "#22d3ee",
    "--primitive-cyan-500": "#06b6d4",
    "--primitive-cyan-600": "#0891b2",
    "--primitive-cyan-700": "#0e7490",
    "--primitive-cyan-800": "#155e75",
    "--primitive-cyan-900": "#164e63",
    "--primitive-purple-50": "#f1e9ff",
    "--primitive-purple-100": "#dfcfff",
    "--primitive-purple-200": "#c2a8ff",
    "--primitive-purple-300": "#a77fff",
    "--primitive-purple-400": "#8a58ff",
    "--primitive-purple-500": "#6e2fff",
    "--primitive-purple-600": "#5826d6",
    "--primitive-purple-700": "#441da3",
    "--primitive-purple-800": "#2e1571",
    "--primitive-purple-900": "#1a0b3e",
    "--primitive-pink-50": "#fef4fa",
    "--primitive-pink-100": "#fce7f3",
    "--primitive-pink-200": "#f6b7d9",
    "--primitive-pink-300": "#f088bd",
    "--primitive-pink-400": "#ea589e",
    "--primitive-pink-500": "#e4287c",
    "--primitive-pink-600": "#be185d",
    "--primitive-pink-700": "#8e1242",
    "--primitive-pink-800": "#5f0c29",
    "--primitive-pink-900": "#2f0613",
    "--primitive-olive-50": "#fafaf0",
    "--primitive-olive-100": "#f3f3dd",
    "--primitive-olive-200": "#e4e4b9",
    "--primitive-olive-300": "#d3d392",
    "--primitive-olive-400": "#c2c26b",
    "--primitive-olive-500": "#aaaa46",
    "--primitive-olive-600": "#808135",
    "--primitive-olive-700": "#666629",
    "--primitive-olive-800": "#49491d",
    "--primitive-olive-900": "#303012",
    "--primitive-ai-50": "#fbf4ff",
    "--primitive-ai-100": "#f5e6ff",
    "--primitive-ai-200": "#e6bcff",
    "--primitive-ai-300": "#d692ff",
    "--primitive-ai-400": "#c668ff",
    "--primitive-ai-500": "#b63eff",
    "--primitive-ai-600": "#a614ff",
    "--primitive-ai-700": "#9100e9",
    "--primitive-ai-800": "#7700bf",
    "--primitive-ai-900": "#5d0095"
  } as Record<PrimitiveToken, string>;
